# -*- coding: utf-8 -*-
"""YFinance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ObOSfm35cLXs5ZPAbnQrnK8GbHuCO5vt
"""

import yfinance as yf
import pandas as pd

def get_stock_data(symbol):
    data = yf.download(symbol)
    print(data.columns)
    prices = data['Close']
    return prices

def YahooData2returns(pricevec):
    n = len(pricevec)
    returns = pricevec[1:n] / pricevec[:n-1] - 1
    return returns

prices = get_stock_data('GS')
print(type(prices))

pricevec = prices.values

returns = YahooData2returns(pricevec)
print(returns)





